config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users

  # AS TRAVELER
  resources :vans, only: [:index, :show] do
    resources :rents, only: [:create]
  end

  # AS TRAVELER
  resources :rents, only: [:index, :show]

  # AS USER
  resource :profile, only: [:show]

  namespace :owner do
    resource :dashboard, only: [:show]

    resources :vans, only: [:new, :create]
    
    resources :rents, only: [] do
      member do
        patch :accept
        patch :decline
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :van
  belongs_to :traveler, class_name: 'User', foreign_key: 'user_id'

  validates :begin_date, :end_date, :state, presence: true
  validates :state, inclusion: { in: %w[pending accepted declined] }
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || begin_date.blank?

    if end_date < begin_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :rent
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :picture, PhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vans, inverse_of: 'owner' # ?????
  has_many :owner_rents, through: :vans, source: :rents

  has_many :rents, inverse_of: 'traveler'

  validates :first_name, :last_name, presence: true

  def owner?
    vans.count.positive?
  end

  def total_earned
    owner_rents.where(state: "accepted").sum(:total_price)
  end
end

app/models/van.rb
class Van < ApplicationRecord
  mount_uploader :picture, PhotoUploader

  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  has_many :rents

  validates :title, :description, :price_per_day, :model, :brand, presence: true
  validates :description, length: { minimum: 10 }

  def available?(date_range = {})
    # GUARD CLAUSE: compare on the today date if there is no range given
    # Return true if there's no rent in this range of date, false if there's
    return true if rents.count.zero?

    if date_range
      start_date = date_range[:begin_date]
      end_date = date_range[:end_date]
    else
      start_date = Date.today
      end_date = Date.today
    end

    rents.all? { |rent| rent.begin_date >= end_date && rent.end_date <= start_date }
  end


  # include PgSearch
  # pg_search_scope :search_by_address,
  #   against: [ :address],
  #   using: {
  #     tsearch: { prefix: true } # <-- now `superman batm` will return something!
  #   }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :picture])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/owner/dashboards_controller.rb
class Owner::DashboardsController < ApplicationController
  def show
    @vans = current_user.vans
    @rents = current_user.owner_rents.order("created_at DESC")
    @pending = @rents.where(state: 'pending')
    @accepted = @rents.where(state: 'accepted')
    @declined = @rents.where(state: 'declined')
  end
end

app/controllers/owner/rents_controller.rb
class Owner::RentsController < ApplicationController
  before_action :set_rent

  def accept
    @rent.update(state: "accepted")

    redirect_to owner_dashboard_path
  end

  def decline
    @rent.update(state: "declined")
    
    redirect_to owner_dashboard_path
  end
  
  private

  def set_rent
    @rent = Rent.find(params[:id])
  end
end

app/controllers/owner/vans_controller.rb
class Owner::VansController < ApplicationController
  def new
    @van = Van.new
  end

  def create
    @van = Van.new(vans_params)
    @van.owner = current_user
    if @van.save
      redirect_to owner_dashboard_path
    else
      render :new
    end
  end

  private

  def vans_params
    params.require(:van).permit(:title, :description, :price_per_day, :model, :brand, :address, :picture)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_van, only: :create

  def index
    @rents = current_user.rents.order(begin_date: :DESC)
  end

  def show
    @rent    = Rent.find(params[:id])
    @van     = @rent.van

    @markers = [{ lat: @van.latitude, lng: @van.longitude }]
  end

  def create
    @rent = Rent.new(rent_params)
    @rent.van = @van
    @rent.traveler = current_user
    @rent.total_price = @van.price_per_day * (@duration + 1)

    if @rent.save
      redirect_to rent_path(@rent)
    else
      redirect_to van_path(@van)
    end
  end

  private

  def set_van
    @van = Van.find(params[:van_id])
  end

  def rent_params
    @duration = (Date.parse(params[:rent][:end_date]) - Date.parse(params[:rent][:begin_date])).to_i
    params.require(:rent).permit("begin_date", "end_date")
  end
end

app/controllers/vans_controller.rb
class VansController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @vans = Van.all
    return @vans unless params[:search]

    q = params[:search]

    if q[:end_date] != '' && q[:end_date] != ""
      @vans = Van.select do |van|
        van.available?(end_date: Date.parse(q[:end_date]), begin_date: Date.parse(q[:begin_date]))
      end
    else
      @vans = Van.all
    end
  end

  def show
    @van = Van.find(params[:id])
    @rent = Rent.new
    @unavailable_dates = unavailable_dates(@van.rents)
  end

  private

  def unavailable_dates(rents)
    unavailable_dates = rents.map do |rent|
      {
        from: rent.begin_date,
        to: rent.end_date
      }
    end

    return unavailable_dates
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Renting awesome vans - Vanbnb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/owner/dashboards/_rents.html.erb
<% rents.each do |rent| %>
  <ul class="list-group">
    <li class="list-group-item-dashboard card-product">
      <div class="image-rent">
      <%= cl_image_tag rent.van.picture, height: 300, width: 300 %>
      </div>
      <div class="card-product-infos card-van-dashboard">
        <div class="card-van-dashboard-infos">
          <div class="info-traveler-dashboard">
            <%= cl_image_tag rent.traveler.picture, height: 100, width: 100, crop: :fill, gravity: :face, class: "avatar-bordered avatar-bordered-dashboard", alt: "avatar-bordered" %>
            <p class="m-0 text-center"><%= rent.traveler.first_name %></p>
          </div>
          <p class="m-0"><%= rent.begin_date.to_formatted_s(:short) %> / <%= rent.end_date.to_formatted_s(:long) %></p>
          <p class="m-0"><%= rent.total_price %> €</p>
        </div>
        <div class="text-right card-van-dashboard-status">
          <% if rent.state == "pending" %>
            <%= link_to "Accept", accept_owner_rent_path(rent), method: :patch, class: "btn btn-success" %>
            <%= link_to "Decline", decline_owner_rent_path(rent), method: :patch, class: "btn btn-danger" %>
          <% else %>
            <%= rent.state %>
          <% end %>
        </div>
      </div>
    </li>
  </ul>
<% end %>

app/views/owner/dashboards/show.html.erb
<div class="container rents-dashboard text-left">
  <div class="d-flex justify-content-between">
    <h2 class="title-dashboard d-inline">My Rents</h2>
    <h3 class="title-dashboard d-inline earn">Earn: <%= current_user.total_earned %> <i class="fas fa-euro-sign"></i></h3>
  </div>
  <div class="tabs">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link nav-pink" id="pills-all-tab" data-toggle="pill" href="#pills-all" role="tab" aria-controls="pills-all" aria-selected="false">All</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active nav-pink" id="pills-pending-tab" data-toggle="pill" href="#pills-pending" role="tab" aria-controls="pills-pending" aria-selected="true">Pending</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-pink" id="pills-accepted-tab" data-toggle="pill" href="#pills-accepted" role="tab" aria-controls="pills-accepted" aria-selected="false">Accepted</a>
      </li>
      <li class="nav-item">
        <a class="nav-link nav-pink" id="pills-declined-tab" data-toggle="pill" href="#pills-declined" role="tab" aria-controls="pills-declined" aria-selected="false">Declined</a>
      </li>
    </ul>

    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-pending" role="tabpanel" aria-labelledby="pills-pending-tab">
        <%= render 'rents', rents: @pending %>
      </div>
      <div class="tab-pane fade" id="pills-all" role="tabpanel" aria-labelledby="pills-all-tab">
        <%= render 'rents', rents: @rents %>
      </div>
      <div class="tab-pane fade" id="pills-accepted" role="tabpanel" aria-labelledby="pills-accepted-tab">
        <%= render 'rents', rents: @accepted %>
      </div>
      <div class="tab-pane fade" id="pills-declined" role="tabpanel" aria-labelledby="pills-declined-tab">
        <%= render 'rents', rents: @declined %>
      </div>
    </div>
  </div>
</div>

<div class="container my-vans">
  <div class="title-dashboard-with-button d-flex justify-content-between">
    <h2 class="d-inline">My Vans</h2>
    <%= link_to 'Add a van', new_owner_van_path, class: "btn btn-light-pink d-inline" %>
  </div>
  <div class="container-dashboard">
    <% @vans.each do |van| %>
      <div class="card-trip card-smaller">
        <%= cl_image_tag van.picture, height: 300, width: 300, crop: :fill %>
        <div class="card-trip-infos">
          <div>
            <h2><%= van.title %></h2>
            <p><%= van.brand %>, <%= van.model %> </p>
          </div>
          <h2 class="card-trip-pricing"><%= van.price_per_day %>€</h2>
        </div>
      </div>
    <% end %>
  </div>
</div>

 

app/views/owner/vans/new.html.erb
<div class="background-image">
<div class="text-center bg-white border-top p-5 header-add-van">
  <div class="col-md-6 offset-md-3">
    <h1 class="title-add" >Please tell me more about your van.</h1>
  </div>
</div>
  <div class="container form-container">
    <%= simple_form_for [:owner, @van] do |f| %>
      <div class="row mt-2 form-add-van">
        <div class="col-md-6 offset-md-3 input-form">
          <div class=" px-2 my-2 remove-border">
            <%= f.input :title, required: false, input_html: { class: "background-color-add" } %>
          </div>
          <div class=" px-2 my-2 remove-border">
            <%= f.input :description, required: false, input_html: { class: "background-color-add" } %>
          </div>
          <div class=" px-2 my-2 remove-border">
            <%= f.input :price_per_day, required: false, input_html: { class: "background-color-add" } %>
          </div>
          <div class=" px-2 my-2 remove-border">
            <%= f.input :brand, required: false, input_html: { class: "background-color-add" } %>
          </div>
          <div class=" px-2 my-2 remove-border">
            <%= f.input :model, required: false, input_html: { class: "background-color-add" } %>
          </div>
          <div class=" px-2 my-2 remove-border">
            <%= f.input :address, input_html: { class: "background-color-add" } %>
          </div>
          <div class=" px-2 my-2 remove-border smaller-div-input">
            <%= f.input  :picture, label_html: { class: "btn btn-primary input-picture" }, input_html: { class: "input-file" }, label: 'Add Picture' %>
            <%= f.input :picture_cache, as: :hidden %>
          </div>
          <%= f.submit 'Create van', class: 'btn btn-add-van'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_path "banner.jpg" %>');">
  <div class="home-content">
    <div class="home-info">
      <h1>Vanbnb brings <strong>awesome vans</strong> to <strong>travelers</strong>!</h1>
      <p>Have a nice experience and rent vans from people near you.</p>
    </div>
    <div class="search__bar">
      <%= render('shared/search-form') %>
    </div>
  </div>
</div>

app/views/rents/_rent.html.erb
<div class="rent__card">
  <div class="top">
    <div class="img__cont">
      <div class="img">
        <%= cl_image_tag rent.van.picture, crop: :fill, class: 'van_img' %>
      </div>
    </div>
  </div>
  <div class="bottom">
    <div class="dates">
      <%= rent.begin_date.to_formatted_s(:short) %> - <%= rent.end_date.to_formatted_s(:short) %>
    </div>
    <div class="adr">
      <%= rent.van.address %>
    </div>
    <div style="margin-top:16px;margin-bottom:16px">
      <div class="line"></div>
    </div>
    <div>
      <div class="details">
        Show the details of the rent
      </div>
    </div>
  </div>
</div>

app/views/rents/create.html.erb
<h1>Rents#create</h1>
<p>Find me in app/views/rents/create.html.erb</p>

app/views/rents/index.html.erb
<div class="rents-container">
  <h2 class="title d-inline">My Rents</h2>

  <div class="rents">
    <% @rents.each do |rent| %>
      <div class="rent">
        <%= link_to (render 'rent', rent: rent), rent_path(rent) %>
      </div>
    <% end %>
  </div>
</div>

app/views/rents/show.html.erb
<div class="rent-container">

  <div class="rent-details">
    <div class="title-rent">
      <h2>Details of your rent</h2>
    </div>
    <div class="image">
      <%= cl_image_tag(@van.picture) %>
      <span class="state-rent"> <%= @rent.state %> </span>
    </div>
    <div class="rent-info">
      <div class="date-rent">
        <p>
          <%= @rent.begin_date.to_formatted_s(:short) %> - <%= @rent.end_date.to_formatted_s(:short) %>.
        </p>
      </div>
      <div class="van-title-rent">
        <h4><%= @van.title %></h4>
      </div>
      <div class="address-rent">
        <p><%= @van.address %></p>
      </div>
    </div>
  </div>

  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  >

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-wagon">
  <!-- Logo section -->
  <div class="navbar-brand">
    <%= link_to "/", class: "navbar-brand" do %>
      <i class="fas fa-shuttle-van"></i>
    <% end %>
    <span class="brand">Vanbnb</span>
  </div>
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon">Vanbnb</span>
  </button> -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <!-- User actions section -->
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My rents", rents_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.picture, width: 100, height: 100, crop: :fill, gravity: "faces", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.owner? %>
              <%= link_to "Owner Dashboard", owner_dashboard_path, class: "dropdown-item" %>
            <% else %>
              <%= link_to "Become an owner", owner_dashboard_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Log out", destroy_user_session_path, method: 'delete', class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn-light-pink btn-signing" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link btn-light-pink btn-signing" %>
        </li>
    <% end %>
    </ul>
  </div>

  <!-- login section -->
</div>

app/views/shared/_search-form.html.erb
<%= simple_form_for :search, url: vans_path, method: :get do |f| %>

  <div class="search__bar_item searchBar_item--when">
    <label for="range_start">When?</label>
    <div class="d-flex" style="height: 30px;">
      <div class="search_when search_when_date_from">
        <%= f.input :begin_date, label: false, as: :string, required: false, placeholder: 'From', input_html: {class: 'datepicker', id: "range_start"} %>
      </div>

      <div class="search_when search_when_sep"></div>

      <div class="search_when search_when_date_to">
        <%= f.input :end_date, label: false, as: :string, required: false, placeholder: 'To', input_html: {class: 'datepicker', id: "range_end"} %>
      </div>
    </div>


  </div>

  <div class="search__bar_item searchBar_item--submit">
    <%= f.submit :Search, class: 'btn btn-light-pink' %>
  </div>
<% end %>

app/views/vans/_search-form.html.erb
<%= simple_form_for :search, url: vans_path, method: :get do |f| %>
  <div class="col-lg-8 col-md-7 col-sm-6 p-0">
    <div class="row">

      <div class="search__bar_item searchBar_item--when">
        <div class="d-flex" style="height: 30px;">
          <div class="search_when search_when_date_from">
            <%= f.input :begin_date, label: false, as: :string, required: false, placeholder: 'From', input_html: {id: "range_start", value: params.dig(:search, :begin_date)} %>
          </div>

          <div class="search_when search_when_sep"></div>

          <div class="search_when search_when_date_to">
            <%= f.input :end_date, label: false, as: :string, required: false, placeholder: 'To', input_html: {id: "range_end", value: params.dig(:search, :end_date)} %>
          </div>
        </div>


      </div>

      <div class="searchBar_item--submit">
        <%= f.submit :Search, class: 'btn btn-light-pink' %>
      </div>
    </div>
  </div>
<% end %>

app/views/vans/_van-card.html.erb
<div class="card-van">
  <div class="card-top" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url('<%= cl_image_path van.picture %>');">
  </div>

  <div class="card-van-infos">
    <div class="card-infos-header">
      <h2><%= van.title %></h2>
      <p class="model"><%= van.brand %> <%= van.model %></p>
    </div>

    <div class="card-price">
      <strong><%= van.price_per_day %>€</strong>
    </div>

  </div>
</div>

app/views/vans/index.html.erb
<div class="van-list">
  <div class="search-container">
    <div class="container">

      <div class="search__bar">
        <%= render 'search-form' %>
      </div>

    </div>
  </div>

  <div class=" container vans-container">
    <% @vans.each do |van| %>
      <div class="van">
        <%= link_to (render 'van-card', van: van), van_path(van, rent: {begin_date: params.dig(:search, :begin_date), end_date: params.dig(:search, :end_date)}) %>
      </div>
    <% end %>
  </div>
</div>

app/views/vans/show.html.erb
<article class="card">
  <div class="card__left">
    <div class="card__image">
      <div class="image">
        <img src="<%= cl_image_path @van.picture, width: 1000, height: 700 %>" />
      </div>
      <!-- <div class="card__sale-flag">Available this week</div> -->
    </div>

    <%= link_to "Go back to list", vans_path(search: {begin_date: params.dig(:rent, :begin_date), end_date: params.dig(:rent, :end_date)}), class: 'back' %>
  </div>

  <div class="card__right">
    <div class="card__info">
      <h2 class="card__title"><%= @van.title %></h2>
      <p><strong><%= @van.brand%> <%= @van.model  %> | <%= @van.address %></strong></p>
      <%= cl_image_tag @van.owner.picture, width: 40, height: 40, crop: 'fill', gravity: 'faces', class: "card-van-owner avatar-bordered" %>
      <div class="card__price"><%= @van.price_per_day %>€</div>
      <p class="card__description">
        <%= @van.description %>
      </p>
      <%= link_to "Rent now", "#rent-van", class: "btn btn-light-pink card__cta" %>
    </div>
  </div>

  <div id="rent-van" class="modal-window">
    <div>
      <div class="card__price"><%= @van.price_per_day %>€/day</div>
      <a href="#" title="Close" class="modal-close">Close</a>

      <div class="rent__form">
        <%= simple_form_for [@van,@rent] do |f| %>

          <div class="form-group row">
            <%= f.input :begin_date, label: 'From', as: :string, required: false, input_html: {class: "rent_datepicker", id: "rent_start_date", value: params[:rent][:begin_date]} %>
          </div>

          <div class="form-group row">
            <%= f.input :end_date, label: 'To', as: :string, required: false, input_html: {class: "rent_datepicker", id: "rent_end_date", value: params[:rent][:end_date]} %>
          </div>

          <div class="form-group row buttons">
            <%= f.submit value: 'Rent', class: "btn btn-light-pink mr-5", id: "rent_btn" %>
            <span class="font-weight-bold d-inline mt-2 hidden" id="total_price"> Total price: </span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div id="unav_dates">
    <%= @unavailable_dates.to_json %>
  </div>
</article>